version: '3.8'

services:
  mlflow_server:
    image: python:3.10-slim
    command: >
      bash -c "pip install mlflow boto3 && 
               mlflow server --host 0.0.0.0 --port 5000 
               --default-artifact-root /mlruns"
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    restart: always

  credit_risk_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    depends_on:
      - mlflow_server
    restart: always

  model_trainer:
    build: .
    command: python src/train.py
    volumes:
      - ./mlruns:/mlruns
      - ./data/processed/:/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    depends_on:
      - mlflow_server